apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: model-registry-lab9
  namespace: rhoai-model-registries   
spec:
  grpc:
    port: 9090
  rest:
    port: 8080
  mysql:
    # NETWORK BRIDGE: We use the full DNS name to reach the lab namespace
    host: "mysql.rhoai-model-registry-lab.svc.cluster.local"
    port: 3306
    database: "sampledb"
    username: "admin"
    passwordSecret:
      name: "registry-db-secret"
      key: "database-password"
    sslMode: "disable"